version: "3.7"
services:
  nginx:
    image: nginx:stable
    container_name: dev_nginx
    ports:
      - 80:80
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - laravel
    networks:
      - paul_net

  # Here we delegate the dependency installation to composer container
  composer:
    image: composer:latest
    user: ${USER_ID}:${GROUP_ID}
    working_dir: /var/www
    volumes:
      - ../../src:/var/www
    command: composer install

  #NodeJs container will simply compile the package.json
  nodejs:
    image: node:lts
    user: ${USER_ID}:${GROUP_ID}
    working_dir: /var/www
    volumes:
      - ../../src:/var/www
    command: npm install

  laravel:
    build:
      context: ./laravel
      args:
        USER_ID: ${USER_ID}
        GROUP_ID: ${GROUP_ID}
    container_name: dev_laravel
    volumes:
      - ../../src:/var/www
      - ./laravel/php-fpm.conf:/usr/local/etc/php-fpm.d/zz-docker.conf
    ports:
      - 42090:9000
    networks:
      - paul_net
    depends_on:
      - composer
      - db

  db:
    image: postgres:12.2
    container_name: dev_postgres
    restart: always
    ports:
      - 5432:5432
    volumes:
      - ./postgres/initScript:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_USER: laravel
      POSTGRES_PASSWORD: passPRO

  adminer:
    image: adminer
    restart: always
    depends_on:
      - db
    ports:
      - 8080:8080

# Docker network
# here we define a small bridge network for all of our containers
networks:
  paul_net:
    driver: bridge
