version: '3.7'
services:
    laravel:
        build: ./laravel
        volumes:
            - ../src/www:var/www

    nginx:
        build: ./nginx
        ports: 
            - 8000:80
        volumes :
            - ../src/www:/var/www
       
