version: "3.7"
services:
  nginx:
    image: nginx:stable
    container_name: dev_nginx
    ports:
      - 80:80
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - laravel
    networks:
      - paul_net

  laravel:
    build:
      context: ./laravel
    container_name: dev_laravel
    volumes:
      - ../../src:/var/www
      - ./laravel/php-fpm.conf:/usr/local/etc/php-fpm.d/zz-docker.conf
    ports:
      - 42090:9000
    networks:
      - paul_net  
    depends_on:
      - db

  db:
    image: postgres:12.2
    container_name: dev_postgres
    restart: always
    ports:
      - 5432:5432
    networks:
      - paul_net
    volumes:
      - ./postgres/initScript:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_USER: laravel
      POSTGRES_PASSWORD: passPRO
    networks:
      - paul_net

# Docker network
# here we define a small bridge network for all of our containers
networks:
  paul_net:
    driver: bridge
