version: "3.7"
services:
  nginx:
    image: nginx:stable
    container_name: prod_nginx
    ports:
      - 8088:80
    volumes:
      - ../../src:/var/www
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - laravel
    networks:
      - paul_net

  laravel:
    build:
      context: ./laravel
    container_name: prod_laravel
    volumes:
      - ../../src:/var/www
      - ./laravel/php-fpm.conf:/usr/local/etc/php-fpm.d/zz-docker.conf
    ports:
      - 42090:9000
    networks:
      - paul_net


# Docker network
# here we define a small bridge network for all of our containers
networks:
  paul_net:
    driver: bridge
