version: '3'
    services:
        laravel:
            build: laravel
        nginx:
            build: nginx

        db:
                build: ./postgres
                restart: always
                # volumes: 
                #     - ./initScript:/docker-entrypoint-initdb.d
                environment: 
                    POSTGRES_USER: pro
                    POSTGRES_PASSWORD: passPRO
            adminer:
                image: adminer
                restart: always
                ports:
                    - 8081:8080
                depends_on: 
                    - db
