name: Laravel
# in this file we describe the action to execute for the CI in the dev pipeline

# based on default laravel workflow
# https://github.com/actions/starter-workflows/blob/master/ci/laravel.yml
on:
  push:
    branches: 
      - v1/fb-github-action # for testing purpose
  pull_request:
    branches: 
      - master
      - develop

jobs:
  laravel-tests:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: Copy .env
      run: php -r "file_exists('.env') || copy('.env.example', '.env');"
      working-directory: ./src
    - name: Install Dependencies
      run: composer install -q --no-ansi --no-interaction --no-scripts --no-suggest --no-progress --prefer-dist
      working-directory: ./src
    - name: Generate key
      run: php artisan key:generate
      working-directory: ./src
    - name: Directory Permissions
      run: chmod -R 777 storage bootstrap/cache
      working-directory: ./src
    - name: Create Database
      run: |
        mkdir -p database
        touch database/database.sqlite
      working-directory: ./src
    - name: Execute tests (Unit and Feature tests) via PHPUnit
      env:
        DB_CONNECTION: sqlite
        DB_DATABASE: database/database.sqlite
      run: vendor/bin/phpunit
      working-directory: ./src
